### PR TITLE
Simplify and optimize Intersect and Subtract

### PR DESCRIPTION
**Pull request by jub0bs**
Hey Jeff! I see that this project is used in Amass, so I decided to take a look and I noticed some minor areas for improvement:

* No need to test for membership in `Subtract`;
* `Intersect` can be simplified quite a bit, as well as optimized (in order to remove one call to `strings.ToLower`).

Incidentally, I also noticed `Set`'s `String` method isn't covered by the tests.;`TestString` doesn't actually rely on `String` at all.  I can push a fix for that as well, if you think that's appropriate as part of the same PR.

### CODE REVIEW

**Comment by caffix** [comment]
Can you create this PR from a branch without force-pushes?

**Comment by jub0bs** [comment]
Hey Jeff. No problem, but may I ask why you insist on having a branch with no force-pushes?

**Comment by caffix** [comment]
A force-push can cause problems with later merges.

The problem:

If you force-push a branch A, you are removing some existing commits from that branch (otherwise you would not need to force). If these commits are also referenced from another branch B, then they will remain in that branch. If you later merge the two branches A and B, A will contain the "new" (forced) commits, and B "old" commits.

In this situation git merge will probably not do what you want. In the best case, you will get merge conflicts. Worst case, you will not but the result will still be wrong. For example, if you removed a commit c1 from A using git rebase -i, if c1 is also in B it will be re-introduced if you merge A and B. That might silently re-introduce a bug :-(.

I prefer that this is avoided.

**Comment by jub0bs** [comment]
What you're describing shouldn't be a problem if the PR's request branch is strictly ahead of the PR's base branch (which is the case in this PR), though. But I can understand why you want to avoid the headaches that come with more complicated cases of force pushes.

**Pull request closed without merging**
